#############################################################################
# Makefile for building: mathapp
# Generated by qmake (2.01a) (Qt 4.7.2) on: Fri Jun 17 22:53:35 2011
# Project:  mathapp.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile mathapp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Factor.cpp \
		main.cpp \
		MathApp.cpp \
		QtFactor.cpp moc_MathApp.cpp \
		moc_QtFactor.cpp
OBJECTS       = Factor.o \
		main.o \
		MathApp.o \
		QtFactor.o \
		moc_MathApp.o \
		moc_QtFactor.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		mathapp.pro
QMAKE_TARGET  = mathapp
DESTDIR       = 
TARGET        = mathapp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_factorapp.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mathapp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile mathapp.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile mathapp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mathapp1.0.0 || $(MKDIR) .tmp/mathapp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mathapp1.0.0/ && $(COPY_FILE) --parents Factor.h MathApp.h QtFactor.h .tmp/mathapp1.0.0/ && $(COPY_FILE) --parents Factor.cpp main.cpp MathApp.cpp QtFactor.cpp .tmp/mathapp1.0.0/ && $(COPY_FILE) --parents factorapp.ui .tmp/mathapp1.0.0/ && (cd `dirname .tmp/mathapp1.0.0` && $(TAR) mathapp1.0.0.tar mathapp1.0.0 && $(COMPRESS) mathapp1.0.0.tar) && $(MOVE) `dirname .tmp/mathapp1.0.0`/mathapp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mathapp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MathApp.cpp moc_QtFactor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MathApp.cpp moc_QtFactor.cpp
moc_MathApp.cpp: ui_factorapp.h \
		QtFactor.h \
		Factor.h \
		MathApp.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MathApp.h -o moc_MathApp.cpp

moc_QtFactor.cpp: Factor.h \
		QtFactor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) QtFactor.h -o moc_QtFactor.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_factorapp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_factorapp.h
ui_factorapp.h: factorapp.ui
	/usr/bin/uic-qt4 factorapp.ui -o ui_factorapp.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Factor.o: Factor.cpp Factor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Factor.o Factor.cpp

main.o: main.cpp MathApp.h \
		ui_factorapp.h \
		QtFactor.h \
		Factor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MathApp.o: MathApp.cpp MathApp.h \
		ui_factorapp.h \
		QtFactor.h \
		Factor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MathApp.o MathApp.cpp

QtFactor.o: QtFactor.cpp QtFactor.h \
		Factor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtFactor.o QtFactor.cpp

moc_MathApp.o: moc_MathApp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MathApp.o moc_MathApp.cpp

moc_QtFactor.o: moc_QtFactor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtFactor.o moc_QtFactor.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

