######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 27 11:31:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Factor.h MathApp.h QtFactor.h
FORMS += factorapp.ui
SOURCES += Factor.cpp main.cpp MathApp.cpp QtFactor.cpp
